<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Moonlight-bugs] [Bug 672697] New: delegate lifetime has a problem
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:moonlight-bugs%40lists.ximian.com?Subject=%5BMoonlight-bugs%5D%20%5BBug%20672697%5D%20New%3A%20delegate%20lifetime%20has%20a%20problem&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="002881.html">
   <LINK REL="Next"  HREF="002893.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Moonlight-bugs] [Bug 672697] New: delegate lifetime has a problem</H1>
    <B>bugzilla_noreply at novell.com</B> 
    <A HREF="mailto:moonlight-bugs%40lists.ximian.com?Subject=%5BMoonlight-bugs%5D%20%5BBug%20672697%5D%20New%3A%20delegate%20lifetime%20has%20a%20problem&In-Reply-To="
       TITLE="[Moonlight-bugs] [Bug 672697] New: delegate lifetime has a problem">bugzilla_noreply at novell.com
       </A><BR>
    <I>Wed Feb 16 14:13:15 EST 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="002881.html">[Moonlight-bugs] [Bug 672517] Codecs installer fails: Failed to	download EULA
</A></li>
        <LI>Next message: <A HREF="002893.html">[Moonlight-bugs] [Bug 672697] delegate lifetime has a problem
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2889">[ date ]</a>
              <a href="thread.html#2889">[ thread ]</a>
              <a href="subject.html#2889">[ subject ]</a>
              <a href="author.html#2889">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
<A HREF="https://bugzilla.novell.com/show_bug.cgi?id=672697">https://bugzilla.novell.com/show_bug.cgi?id=672697</A>

<A HREF="https://bugzilla.novell.com/show_bug.cgi?id=672697#c0">https://bugzilla.novell.com/show_bug.cgi?id=672697#c0</A>


           Summary: delegate lifetime has a problem
    Classification: Mono
           Product: Moonlight
           Version: SVN
          Platform: x86
        OS/Version: SLED 11
            Status: NEW
          Severity: Normal
          Priority: P5 - None
         Component: engine
        AssignedTo: <A HREF="http://lists.ximian.com/mailman/listinfo/moonlight-bugs">moonlight-bugs at lists.ximian.com</A>
        ReportedBy: <A HREF="http://lists.ximian.com/mailman/listinfo/moonlight-bugs">rui at ruicraveiro.com</A>
         QAContact: <A HREF="http://lists.ximian.com/mailman/listinfo/moonlight-bugs">moonlight-bugs at lists.ximian.com</A>
          Found By: ---
           Blocker: ---


Created an attachment (id=414493)
 --&gt; (<A HREF="http://bugzilla.novell.com/attachment.cgi?id=414493">http://bugzilla.novell.com/attachment.cgi?id=414493</A>)
Exception that is being caught

User-Agent:       Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/534.10
(KHTML, like Gecko) Chrome/8.0.552.237 Safari/534.10

Hi, very very occasionally my application is having an exception when loading.
This is happening very rarely, so I am having a very hard time reproducing it.

I am attaching the exception I am catching. It is the wrong exception, however,
since the method it comes from is the following:

            try
            {
                updatingRegionsListeners.Raise(null, EventArgs.Empty);
            }
            catch (TargetInvocationException ex)
            {
                Exception rootException = ex.GetRootException();

                throw new
UpdateRegionsException(string.Format(CultureInfo.CurrentCulture,
                    Resources.UpdateRegionException, rootException),
ex.InnerException);
            }

So, what we are seeing is a new exception in the catch block and not the
original one. I've tried to out-comment the try/catch and leave just the
content of the try, but still didn't succeed in reproducing again the bug.

However, digging a little deeper into the code, the following method is being
called:


        public void Raise(params object[] args)
        {
            this.listeners.RemoveAll(listener =&gt; listener.Target == null);
            // I later added this here: GC.Collect();
            foreach (Delegate handler in
this.listeners.ToList().Select(listener =&gt; listener.Target).Where(listener =&gt;
listener != null))
            {
                handler.DynamicInvoke(args);
            }
        }

Suspecting the indeterminism of the exception is related to when GC kicks in, I
tried to force the GC, where you can find the comment // I later added this
here: GC.Collect()

After trying a few more times, I had not an exception, but in fact a crash, the
output of which I am also attaching to this bug.

Reproducible: Sometimes

Steps to Reproduce:
1.
2.
3.
Actual Results:  
a so far unknown exception (or with the GC.Collect() in place, a crash), that
happens only very rarely and under yet to determine conditions.

Expected Results:  
no exception, no crash :-)

-- 
Configure bugmail: <A HREF="https://bugzilla.novell.com/userprefs.cgi?tab=email">https://bugzilla.novell.com/userprefs.cgi?tab=email</A>
------- You are receiving this mail because: -------
You are the QA contact for the bug.
You are the assignee for the bug.
</PRE>









<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="002881.html">[Moonlight-bugs] [Bug 672517] Codecs installer fails: Failed to	download EULA
</A></li>
	<LI>Next message: <A HREF="002893.html">[Moonlight-bugs] [Bug 672697] delegate lifetime has a problem
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2889">[ date ]</a>
              <a href="thread.html#2889">[ thread ]</a>
              <a href="subject.html#2889">[ subject ]</a>
              <a href="author.html#2889">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/moonlight-bugs">More information about the Moonlight-bugs
mailing list</a><br>
</body></html>
