<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 76249][Nor] New - Wrong exception for certain
	Socket calls when Socket has been disposed
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%2076249%5D%5BNor%5D%20New%20-%20Wrong%20exception%20for%20certain%0A%09Socket%20calls%20when%20Socket%20has%20been%20disposed&In-Reply-To=bug-76249%40chernobyl.ximian.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="034172.html">
   <LINK REL="Next"  HREF="034174.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 76249][Nor] New - Wrong exception for certain
	Socket calls when Socket has been disposed</H1>
    <B>bugzilla-daemon at bugzilla.ximian.com</B> 
    <A HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%2076249%5D%5BNor%5D%20New%20-%20Wrong%20exception%20for%20certain%0A%09Socket%20calls%20when%20Socket%20has%20been%20disposed&In-Reply-To=bug-76249%40chernobyl.ximian.com"
       TITLE="[Mono-bugs] [Bug 76249][Nor] New - Wrong exception for certain
	Socket calls when Socket has been disposed">bugzilla-daemon at bugzilla.ximian.com
       </A><BR>
    <I>Tue Sep 27 13:27:18 EDT 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="034172.html">[Mono-bugs] [Bug 76184][Wis] Changed - win32 gacutil shouldn't
	install *.config files for dlls
</A></li>
        <LI>Next message: <A HREF="034174.html">[Mono-bugs] [Bug 76249][Nor] Changed - Wrong exception for certain
	Socket calls when Socket has been disposed
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#34173">[ date ]</a>
              <a href="thread.html#34173">[ thread ]</a>
              <a href="subject.html#34173">[ subject ]</a>
              <a href="author.html#34173">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Please do not reply to this email- if you want to comment on the bug, go to the
URL shown below and enter your comments there.

Changed by <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">jlarimer at gmail.com.</A>

<A HREF="http://bugzilla.ximian.com/show_bug.cgi?id=76249">http://bugzilla.ximian.com/show_bug.cgi?id=76249</A>

--- shadow/76249	2005-09-27 13:27:17.000000000 -0400
+++ shadow/76249.tmp.15719	2005-09-27 13:27:17.000000000 -0400
@@ -0,0 +1,102 @@
+Bug#: 76249
+Product: Mono: Class Libraries
+Version: 1.1
+OS: All
+OS Details: Tested on Fedora Core 4
+Status: NEW   
+Resolution: 
+Severity: 
+Priority: Normal
+Component: System
+AssignedTo: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at ximian.com</A>                            
+ReportedBy: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">jlarimer at gmail.com</A>               
+QAContact: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at ximian.com</A>
+TargetMilestone: ---
+URL: 
+Cc: 
+Summary: Wrong exception for certain Socket calls when Socket has been disposed
+
+Please fill in this template when reporting a bug, unless you know what you
+are doing.
+Description of Problem:
+
+When a Socket is closed, any attempt to perform operations on it should
+generate a System.ObjectDisposedException. Currently, there are some calls
+in Socket.cs that don't check for disposal and generate a
+System.NullReferenceException. Also, the behavior causes various problems
+debugging with gdb since a SIGSEGV happens.
+
+&gt; Steps to reproduce the problem:
+1. Compile this as socktest.exe:
+
+using System;
+using System.Net;
+using System.Net.Sockets;
+
+class socketest {
+	static void Main(string[] args) {
+		Socket s = new Socket(AddressFamily.InterNetwork, SocketType.Dgram,
+ProtocolType.Udp);
+
+		byte[] buf = new byte[100];
+		EndPoint ep = new IPEndPoint(IPAddress.Any, 31337);
+		s.Close();
+
+		s.ReceiveFrom(buf, ref ep);
+	}
+}
+
+2. Run under Microsoft.NET, the exception thrown is:
+
+Unhandled Exception: System.ObjectDisposedException: Cannot access a
+disposed object named &quot;System.Net.Sockets.Socket&quot;.
+Object name: &quot;System.Net.Sockets.Socket&quot;.
+   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset,
+Int32 size, SocketFlags socketFlags, EndPoint&amp; remoteEP)
+   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, EndPoint&amp; remoteEP)
+   at socketest.Main(String[] args) in c:\projects\socktest\class1.cs:line 13
+
+3. Run under Mono, the Exception thrown is:
+
+Unhandled Exception: System.NullReferenceException: Object reference not
+set to an instance of an object
+in &lt;0x00000&gt; &lt;unknown method&gt;
+in (wrapper managed-to-native) System.Net.Sockets.Socket:RecvFrom_internal
+(intptr,byte[],int,int,System.Net.Sockets.SocketFlags,System.Net.SocketAddress&amp;,int&amp;)
+in &lt;0x0004b&gt; System.Net.Sockets.Socket:ReceiveFrom_nochecks (System.Byte[]
+buf, Int32 offset, Int32 size, SocketFlags flags, System.Net.EndPoint
+remote_end)
+in &lt;0x0002c&gt; System.Net.Sockets.Socket:ReceiveFrom (System.Byte[] buf,
+System.Net.EndPoint remote_end)
+in &lt;0x0007d&gt; socktest.Class1:Main (System.String[] args)
+
+4. In GDB, this happens:
+
+Program received signal SIGSEGV, Segmentation fault.
+[Switching to Thread -1209063744 (LWP 28173)]
+0x08120c90 in _wapi_handle_type (handle=0xffffffff)
+    at ../../mono/io-layer/handles-private.h:114
+114             return(_WAPI_PRIVATE_HANDLES(idx).type);
+
+
+This is because the handle is -1 when _wapi_handle_type gets called. That
+code should probably never get called... Sockets.cs handles the case for
+disposed sockets for some methods, but not others.
+
+
+&gt; How often does this happen? 
+
+Every time
+
+&gt; Additional Information:
+
+Propsed patch attached. After applying the patch, the results are as expected:
+
+Unhandled Exception: System.ObjectDisposedException: The object was used
+after being disposed.
+in [0x0005a] (at
+/home/jlarimer/mono-dev/mcs/class/System/System.Net.Sockets/Socket.cs:1410)
+System.Net.Sockets.Socket:ReceiveFrom (System.Byte[] buf,
+System.Net.EndPoint remote_end)
+in [0x0002c] (at /home/jlarimer/test/socketest/socktest.cs:27)
+socktest.Class1:Main (System.String[] args)
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="034172.html">[Mono-bugs] [Bug 76184][Wis] Changed - win32 gacutil shouldn't
	install *.config files for dlls
</A></li>
	<LI>Next message: <A HREF="034174.html">[Mono-bugs] [Bug 76249][Nor] Changed - Wrong exception for certain
	Socket calls when Socket has been disposed
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#34173">[ date ]</a>
              <a href="thread.html#34173">[ thread ]</a>
              <a href="subject.html#34173">[ subject ]</a>
              <a href="author.html#34173">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-bugs">More information about the mono-bugs
mailing list</a><br>
</body></html>
