<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [MonoTouch] ConnectFailure error causes app to cease connecting	externally
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:monotouch%40lists.ximian.com?Subject=%5BMonoTouch%5D%20ConnectFailure%20error%20causes%20app%20to%20cease%20connecting%0A%09externally&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="006101.html">
   <LINK REL="Next"  HREF="006012.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[MonoTouch] ConnectFailure error causes app to cease connecting	externally</H1>
    <B>bamagrad03</B> 
    <A HREF="mailto:monotouch%40lists.ximian.com?Subject=%5BMonoTouch%5D%20ConnectFailure%20error%20causes%20app%20to%20cease%20connecting%0A%09externally&In-Reply-To="
       TITLE="[MonoTouch] ConnectFailure error causes app to cease connecting	externally">daniel at ilogicweb.net
       </A><BR>
    <I>Sun Oct 23 22:49:26 EDT 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="006101.html">[MonoTouch] UITabBarController with UISplitViewController
</A></li>
        <LI>Next message: <A HREF="006012.html">[MonoTouch] ConnectFailure error causes app to cease connecting	externally
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5996">[ date ]</a>
              <a href="thread.html#5996">[ thread ]</a>
              <a href="subject.html#5996">[ subject ]</a>
              <a href="author.html#5996">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I've got an app that does a number of externally focused things: twitter via
oAuth, connecting to my web server services, etc. And everything works
great, but after about 3-4 minutes of heavy use, the app starts throwing:

Error: ConnectFailure (System call failed)

More specifically:

  at System.Net.HttpWebRequest.EndGetRequestStream (IAsyncResult
asyncResult) [0x00000] in &lt;filename unknown&gt;:0 
  at System.Net.HttpWebRequest.GetRequestStream () [0x00000] in &lt;filename
unknown&gt;:0 
  at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke
(System.String method_name, System.Object[] parameters) [0x00000] in
&lt;filename unknown&gt;:0 

Now, I can trap for this. But the bigger issue is, once I get this error,
the app NEVER recovers. It won't connect to my RSS feeds, Twitter oAuth, or
any of my webservices. I continue to get the same connectfailure error until
I restart the app.

Could this be a case of me not disposing manually of some resource that I
should be? Here's some code from my webservice data pull, but keep in mind,
this is only one of many ways I connect.

List&lt;BBStandings&gt; rank = new List&lt;BBStandings&gt;();
			try{
			var service = new ServiceName.Service();
			
			XmlDocument xmlDoc = new XmlDocument();
			xmlDoc.LoadXml(service.GetStandings());
			
			string s = xmlDoc.InnerXml;
			-- bunch of variables declared
			int iCount = 1;
			
			if (s != &quot;&lt;NewDataSet /&gt;&quot;)
			{
			System.Xml.XmlTextReader xml = new System.Xml.XmlTextReader(new
System.IO.StringReader(s));
			int iXML = 0;
			
			while (xml.Read())
			{	
				switch (xml.NodeType)
				{
					case XmlNodeType.EndElement:
						iCount = 1;
						sElement = &quot;&quot;;
						sText = &quot;&quot;;
						break;
					case XmlNodeType.Element:
						sElement = xml.Name;
						iCount = 2;
						break;
					case XmlNodeType.Text:
						//sElement = xml.Name;
						sText = xml.Value;
						iCount = 3;
						break;
				}
				if (iCount == 3)
				{
					switch (sElement)
					{
					case &quot;TeamID&quot;:
						sTeamID = sText;
						iCount = 1;
						break;
					case &quot;TeamName&quot;:						
						sTeamName = sText;
						iCount = 1;
						break;
					case &quot;ConferenceRecord&quot;:						
						sConferenceRecord = sText;
						iCount = 1;
						break;
					case &quot;Record&quot;:
						sRecord = sText;
						BBStandings r = new BBStandings();
						
						r.TeamID = Convert.ToInt32(sTeamID);
						r.TeamName = sTeamName;
						
						r.ConferenceRecord = sConferenceRecord;
						
						r.Record = sRecord;
						 
						rank.Insert(iXML, r);
						
						iXML += 1;
						sTeamID = &quot;&quot;;
						sConferenceRecord = &quot;&quot;;
					
						sTeamName = &quot;&quot;;
						sRecord = &quot;&quot;;
						sText = &quot;&quot;;
						sElement = &quot;&quot;;
						break;
					}
				}
			}
			}
			}
			catch (Exception ex)
			{
				string s=ex.Message;
			}
			return rank; 

I'm running MD 2.6.0.1
MonoFramework 2.10.5
MT 4.2.2


--
View this message in context: <A HREF="http://monotouch.2284126.n4.nabble.com/ConnectFailure-error-causes-app-to-cease-connecting-externally-tp3931899p3931899.html">http://monotouch.2284126.n4.nabble.com/ConnectFailure-error-causes-app-to-cease-connecting-externally-tp3931899p3931899.html</A>
Sent from the MonoTouch mailing list archive at Nabble.com.
</PRE>








































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="006101.html">[MonoTouch] UITabBarController with UISplitViewController
</A></li>
	<LI>Next message: <A HREF="006012.html">[MonoTouch] ConnectFailure error causes app to cease connecting	externally
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5996">[ date ]</a>
              <a href="thread.html#5996">[ thread ]</a>
              <a href="subject.html#5996">[ subject ]</a>
              <a href="author.html#5996">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/monotouch">More information about the MonoTouch
mailing list</a><br>
</body></html>
