<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-devel-list] Re: [Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-devel-list%40lists.ximian.com?Subject=%5BMono-devel-list%5D%20Re%3A%20%5BMono-list%5D%20exceptions%20are%20not%20thrown%20from%20ThreadPool%27ed%0A%20thread%20objects%3F&In-Reply-To=41750417.3000804%40itcsoluciones.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="008372.html">
   <LINK REL="Next"  HREF="008387.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-devel-list] Re: [Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?</H1>
    <B>gennady wexler</B> 
    <A HREF="mailto:mono-devel-list%40lists.ximian.com?Subject=%5BMono-devel-list%5D%20Re%3A%20%5BMono-list%5D%20exceptions%20are%20not%20thrown%20from%20ThreadPool%27ed%0A%20thread%20objects%3F&In-Reply-To=41750417.3000804%40itcsoluciones.com"
       TITLE="[Mono-devel-list] Re: [Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?">adyler at winisp.net
       </A><BR>
    <I>Tue Oct 19 12:43:48 EDT 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="008372.html">[Mono-devel-list] Re: [Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
</A></li>
        <LI>Next message: <A HREF="008387.html">[Mono-devel-list] Re: [Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#8377">[ date ]</a>
              <a href="thread.html#8377">[ thread ]</a>
              <a href="subject.html#8377">[ subject ]</a>
              <a href="author.html#8377">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>how about mono? can you see it not working when run under mono? including
1.1.1? then we need to bug this. would be nice if someone on monodev can
comment on this. is this an unsupported scenario?


On 10/19/04 5:09 AM, &quot;Mariano Alarcon&quot; &lt;<A HREF="http://lists.ximian.com/mailman/listinfo/mono-devel-list">marianoa at itcsoluciones.com</A>&gt; wrote:

&gt;<i> It works as expected with ms.net without having to uncomment anything.
</I>&gt;<i> 
</I>&gt;<i> gennady wexler wrote:
</I>&gt;<i> 
</I>&gt;&gt;<i> has anyone noticed this problem? that is if you have a ThreadPool'ed thread
</I>&gt;&gt;<i> object created, any exception thrown inside of that thread will not be
</I>&gt;&gt;<i> rethrown up at all. I ran into this accidentally while developing some
</I>&gt;&gt;<i> performance code..
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> here's an example, could someone please try this with .net compiler/runtime?
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> if you just compile and run it, the exception in _ThreadProc does not get
</I>&gt;&gt;<i> thrown.
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> now, if you uncomment regular thread definition below &quot;ThreadPool&quot; - you
</I>&gt;&gt;<i> will get &quot;exception 2&quot; get thrown.
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> any ideas? is this expected? I hope not...
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> using System;
</I>&gt;&gt;<i> using System.Threading;
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> public class main {
</I>&gt;&gt;<i>        static void Main() {
</I>&gt;&gt;<i>                // this will not throw exception 1 (seems to be a bug?)
</I>&gt;&gt;<i>                ThreadPool.UnsafeQueueUserWorkItem(new
</I>&gt;&gt;<i>                        WaitCallback(_ThreadProc), null);
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i>                // uncomment this to thrown exception 2 (as expected)
</I>&gt;&gt;<i>                // new Thread(new ThreadStart(_ThreadProc2)).Start();
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i>                Thread.Sleep(90000);
</I>&gt;&gt;<i>        }
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i>        private static void _ThreadProc(Object state) {
</I>&gt;&gt;<i>                throw new Exception(&quot;exception 1&quot;);
</I>&gt;&gt;<i>        }
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i>        private static void _ThreadProc2() {
</I>&gt;&gt;<i>                throw new Exception(&quot;exception 2&quot;);
</I>&gt;&gt;<i>        }
</I>&gt;&gt;<i> }
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i> _______________________________________________
</I>&gt;&gt;<i> Mono-list maillist  -  <A HREF="http://lists.ximian.com/mailman/listinfo/mono-devel-list">Mono-list at lists.ximian.com</A>
</I>&gt;&gt;<i> <A HREF="http://lists.ximian.com/mailman/listinfo/mono-list">http://lists.ximian.com/mailman/listinfo/mono-list</A>
</I>&gt;&gt;<i> 
</I>&gt;&gt;<i>  
</I>&gt;&gt;<i> 
</I>&gt;<i> 
</I>


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="008372.html">[Mono-devel-list] Re: [Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
</A></li>
	<LI>Next message: <A HREF="008387.html">[Mono-devel-list] Re: [Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#8377">[ date ]</a>
              <a href="thread.html#8377">[ thread ]</a>
              <a href="subject.html#8377">[ subject ]</a>
              <a href="author.html#8377">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-devel-list">More information about the Mono-devel-list
mailing list</a><br>
</body></html>
