<tt>
&lt;div&gt;I&nbsp;have&nbsp;been&nbsp;happily&nbsp;running&nbsp;mono&nbsp;2.11.1&nbsp;cross-compiled&nbsp;for&nbsp;MIPS&nbsp;with&nbsp;gcc&nbsp;4.5.3-1.2. &nbsp;Out&nbsp;of&nbsp;nearly&nbsp;500&nbsp;runtime&nbsp;tests,&nbsp;only&nbsp;async-exc-compilation.exe &nbsp;and&nbsp;monitor.exe&nbsp;were&nbsp;failing&nbsp;(hangs). &nbsp;&lt;font&nbsp;face=&quot;arial,helvetica,sans-serif&quot;&gt;Recenly&nbsp;our&nbsp;SOC&nbsp;vendor&nbsp;upgraded&nbsp;us&nbsp;&lt;/font&gt;&lt;font&nbsp;face=&quot;arial,helvetica,sans-serif&quot;&gt;from&nbsp;2.6.37-2.2&nbsp;to&nbsp;-2.8,&nbsp;which&nbsp;has&nbsp;caused&nbsp;a&nbsp;significant&nbsp;regression&nbsp;in&nbsp;functionality:&nbsp;117&nbsp;of&nbsp;the&nbsp;runtime&nbsp;tests&nbsp;now&nbsp;fail. &nbsp;It&nbsp;appears&nbsp;the&nbsp;culprit&nbsp;in&nbsp;many&nbsp;of&nbsp;the&nbsp;failures&nbsp;is&nbsp;the&nbsp;use&nbsp;of&nbsp;try-catch. &nbsp;The&nbsp;following&nbsp;simple&nbsp;program&nbsp;demonstrates&nbsp;the&nbsp;problem:&lt;/font&gt;&lt;/div&gt;<br>
<br>
&lt;div&gt; &lt;/div&gt;<br>
&lt;div&gt;using&nbsp;System;&lt;/div&gt;<br>
&lt;div&gt;namespace&nbsp;trycatch&lt;br&gt;{&lt;br&gt;   &nbsp;class&nbsp;MainClass&lt;br&gt;   &nbsp;{&lt;br&gt;       &nbsp;public&nbsp;static&nbsp;void&nbsp;Main&nbsp;(string[]&nbsp;args)&lt;br&gt;       &nbsp;{&lt;br&gt;           &nbsp;int[]&nbsp;array&nbsp;=&nbsp;new&nbsp;int[5]&nbsp;{10,&nbsp;20,&nbsp;30,&nbsp;40,&nbsp;50};&lt;br&gt;           &nbsp;try&nbsp;{&lt;br&gt;               &nbsp;Console.WriteLine(&quot;Entering&nbsp;first&nbsp;try&nbsp;clause:&quot;);&lt;br&gt;<br>
           &nbsp;}&nbsp;catch&nbsp;{&lt;br&gt;               &nbsp;Console.WriteLine(&quot;Entering&nbsp;first&nbsp;catch&nbsp;clause&quot;);&lt;br&gt;           &nbsp;}&lt;br&gt;           &nbsp;try&nbsp;{&lt;br&gt;               &nbsp;Console.WriteLine(&quot;Entering&nbsp;second&nbsp;try&nbsp;clause:&nbsp;array[5]={0}&quot;,&nbsp;array[5]);&lt;br&gt;<br>
           &nbsp;}&nbsp;catch&nbsp;{&lt;br&gt;               &nbsp;Console.WriteLine(&quot;Entering&nbsp;second&nbsp;catch&nbsp;clause&quot;);&lt;br&gt;           &nbsp;}&lt;br&gt;       &nbsp;}&lt;br&gt;   &nbsp;}&lt;br&gt;}&lt;br&gt;&lt;/div&gt;<br>
&lt;div&gt;Before,&nbsp;the&nbsp;expected&nbsp;behavior&nbsp;was&nbsp;seen:&lt;/div&gt;<br>
&lt;div&gt; &lt;/div&gt;<br>
&lt;div&gt;#&nbsp;mono&nbsp;trycatch.exe&lt;br&gt;Entering&nbsp;first&nbsp;try&nbsp;clause:&lt;br&gt;Entering&nbsp;second&nbsp;catch&nbsp;clause&lt;br&gt;&lt;/div&gt;<br>
&lt;div&gt;Now,&nbsp;raising&nbsp;the&nbsp;exception&nbsp;in&nbsp;the&nbsp;second&nbsp;try-catch&nbsp;block&nbsp;aborts&nbsp;the&nbsp;program:&lt;/div&gt;<br>
&lt;div&gt; &lt;/div&gt;<br>
&lt;div&gt;#&nbsp;mono&nbsp;trycatch.exe&lt;br&gt;Entering&nbsp;first&nbsp;try&nbsp;clause:&lt;br&gt;Stacktrace:&lt;/div&gt;<br>
&lt;div&gt; &lt;/div&gt;<br>
&lt;div&gt;Aborted&lt;br&gt;&lt;/div&gt;<br>
&lt;div&gt;Has&nbsp;anyone&nbsp;seen&nbsp;behavior&nbsp;like&nbsp;this? &nbsp;Any&nbsp;ideas&nbsp;where&nbsp;to&nbsp;start&nbsp;looking?&lt;/div&gt;<br>
&lt;div&gt; &lt;/div&gt;<br>
&lt;div&gt;TMM&lt;/div&gt;<br>
&lt;div&gt; &lt;/div&gt;<br>

</tt>
