<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 58707][Maj] Changed - Exception when trying to AppDomain.Unload()
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:bugzilla-daemon%40bugzilla.ximian.com">
   <META NAME="robots" CONTENT="index,nofollow">
   
   <LINK REL="Previous"  HREF="017094.html">
   <LINK REL="Next"  HREF="017096.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 58707][Maj] Changed - Exception when trying to AppDomain.Unload()
   </H1>
    <B>bugzilla-daemon@bugzilla.ximian.com
    </B> 
    <A HREF="mailto:bugzilla-daemon%40bugzilla.ximian.com"
       TITLE="[Mono-bugs] [Bug 58707][Maj] Changed - Exception when trying to AppDomain.Unload()">bugzilla-daemon@bugzilla.ximian.com
       </A><BR>
    <I>Wed,  9 Jun 2004 10:21:20 -0400 (EDT)</I>
    <P><UL>
        <LI> Previous message: <A HREF="017094.html">[Mono-bugs] [Bug 59638][Blo] Changed - MONO Beta 2 bug with XmlSerializer member ordering
</A></li>
        <LI> Next message: <A HREF="017096.html">[Mono-bugs] [Bug 58707][Maj] Changed - Exception when trying to AppDomain.Unload()
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#17095">[ date ]</a>
              <a href="thread.html#17095">[ thread ]</a>
              <a href="subject.html#17095">[ subject ]</a>
              <a href="author.html#17095">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Please do not reply to this email- if you want to comment on the bug, go to the
URL shown below and enter your comments there.

Changed by <A HREF="mailto:robik@mailbox.sk.">robik@mailbox.sk.</A>

<A HREF="http://bugzilla.ximian.com/show_bug.cgi?id=58707">http://bugzilla.ximian.com/show_bug.cgi?id=58707</A>

--- shadow/58707	2004-05-25 16:28:32.000000000 -0400
+++ shadow/58707.tmp.28700	2004-06-09 10:21:20.000000000 -0400
@@ -1,13 +1,13 @@
 Bug#: 58707
 Product: Mono: Runtime
 Version: unspecified
 OS: unknown
 OS Details: Fedora Core 1, kernel linux-2.4.22-1.2188.nptl
-Status: RESOLVED   
-Resolution: FIXED
+Status: REOPENED   
+Resolution: 
 Severity: 040 One week
 Priority: Major
 Component: misc
 AssignedTo: <A HREF="mailto:lluis@ximian.com">lluis@ximian.com</A>                            
 ReportedBy: <A HREF="mailto:robik@mailbox.sk">robik@mailbox.sk</A>               
 QAContact: <A HREF="mailto:mono-bugs@ximian.com">mono-bugs@ximian.com</A>
@@ -173,6 +173,129 @@
 1039:	value /= 10;
 1040: }
 
 
 ------- Additional Comments From <A HREF="mailto:vargaz@freemail.hu">vargaz@freemail.hu</A>  2004-05-25 16:28 -------
 Fixed in CVS.
+
+------- Additional Comments From <A HREF="mailto:robik@mailbox.sk">robik@mailbox.sk</A>  2004-06-09 10:21 -------
+Hi!
+
+It seems, something is broken again.
+
+Result for 1. test:
+
+AppDomainTest:Main() Entered
+AppDomainTest:DoTest()
+ 
+** (AppDomainTest.exe:16096): WARNING **: : unref on 17 called when 
+ref was already 0
+AppDomainTest:Main() Exited
+ 
+** ERROR **: file gc.c: line 424 
+(ves_icall_System_GCHandle_FreeHandle): assertion failed: (type == 
+gc_handle_types [idx])
+aborting...
+Aborted
+
+
+Result for 2. test:
+
+AppDomainTest:Main() Entered
+AppDomainTest:DoTest()
+ 
+** (AppDomainTest.exe:16113): WARNING **: : unref on 17 called when 
+ref was already 0
+AppDomainTest:DoTest()
+ 
+** (AppDomainTest.exe:16113): WARNING **: : unref on 24 called when 
+ref was already 0
+ 
+Unhandled Exception: System.NullReferenceException: Object reference 
+not set to an instance of an object
+ 
+** (AppDomainTest.exe:16112): WARNING **: Finalization of domain Test 
+2 timed out.
+ 
+Unhandled Exception: System.CannotUnloadAppDomainException: 
+Finalization of domain Test 2 timed out.
+in (unmanaged) (wrapper managed-to-native) 
+System.AppDomain:InternalUnload (int)in &lt;0x00004&gt; (wrapper managed-to-
+native) System.AppDomain:InternalUnload (int)
+in &lt;0x00049&gt; System.AppDomain:Unload (System.AppDomain)
+in &lt;0x001fe&gt; AppDomainTest.AppDomainTest:Main ()
+ 
+another result for 2. test:
+
+AppDomainTest:Main() Entered
+AppDomainTest:DoTest()
+ 
+Unhandled Exception: System.NullReferenceException: Object reference 
+not set to an instance of an object
+ 
+Server stack trace:
+in (unmanaged) System.Threading.Thread:Start ()
+in &lt;0x00156&gt; System.Threading.Timer:Init 
+(System.Threading.TimerCallback,object,int,int)
+in &lt;0x0008e&gt; (wrapper remoting-invoke-with-check) 
+System.Threading.Timer:Init 
+(System.Threading.TimerCallback,object,int,int)
+in &lt;0x00082&gt; System.Threading.Timer:.ctor 
+(System.Threading.TimerCallback,object,int,int)
+in &lt;0x00095&gt; System.Threading.Timer:.ctor 
+(System.Threading.TimerCallback,object,System.TimeSpan,System.TimeSpan
+)
+in &lt;0x000f4&gt; (wrapper remoting-invoke-with-check) 
+System.Threading.Timer:.ctor 
+(System.Threading.TimerCallback,object,System.TimeSpan,System.TimeSpan
+)
+in &lt;0x000b3&gt; 
+System.Runtime.Remoting.Lifetime.LeaseManager:StartManager ()
+in &lt;0x0007b&gt; 
+System.Runtime.Remoting.Lifetime.LeaseManager:TrackLifetime 
+(System.Runtime.Remoting.ServerIdentity)
+in &lt;0x00015&gt; 
+System.Runtime.Remoting.Lifetime.LifetimeServices:TrackLifetime 
+(System.Runtime.Remoting.ServerIdentity)
+in &lt;0x001c1&gt; 
+System.Runtime.Remoting.ServerIdentity:StartTrackingLifetime 
+(System.Runtime.Remoting.Lifetime.ILease)
+in &lt;0x0012f&gt; 
+System.Runtime.Remoting.RemotingServices:CreateClientActivatedServerId
+entity (System.MarshalByRefObject,System.Type,string)
+in &lt;0x0028b&gt; System.Runtime.Remoting.RemotingServices:Marshal 
+(System.MarshalByRefObject,string,System.Type)
+in &lt;0x00015&gt; System.Runtime.Remoting.RemotingServices:Marshal 
+(System.MarshalByRefObject)
+in &lt;0x000ff&gt; 
+System.Runtime.Remoting.Messaging.CADMessageBase:MarshalArgument 
+(object,System.Collections.ArrayList&amp;)
+in &lt;0x0009e&gt; 
+System.Runtime.Remoting.Messaging.CADMethodReturnMessage:.ctor 
+(System.Runtime.Remoting.Messaging.IMethodReturnMessage)
+in &lt;0x000b3&gt; 
+System.Runtime.Remoting.Messaging.CADMethodReturnMessage:Create 
+(System.Runtime.Remoting.Messaging.IMessage)
+in &lt;0x00089&gt; System.AppDomain:ProcessMessageInDomain (byte
+[],System.Runtime.Remoting.Messaging.CADMethodCallMessage,byte[]
+&amp;,System.Runtime.Remoting.Messaging.CADMethodReturnMessage&amp;)
+in &lt;0x00094&gt; (wrapper remoting-invoke-with-check) 
+System.AppDomain:ProcessMessageInDomain (byte
+[],System.Runtime.Remoting.Messaging.CADMethodCallMessage,byte[]
+&amp;,System.Runtime.Remoting.Messaging.CADMethodReturnMessage&amp;)
+in &lt;0x0004b&gt; 
+System.Runtime.Remoting.Channels.CrossAppDomainSink:ProcessMessageInDo
+main (byte[],System.Runtime.Remoting.Messaging.CADMethodCallMessage)
+ 
+ 
+Exception rethrown at [0]:
+ 
+in &lt;0x00748&gt; System.Runtime.Remoting.Proxies.RealProxy:PrivateInvoke 
+(System.Runtime.Remoting.Proxies.RealProxy,System.Runtime.Remoting.Mes
+saging.IMessage,System.Exception&amp;,object[]&amp;)
+ 
+ 
+Unhandled Exception: System.NullReferenceException: A null value was 
+found where an object instance was required.
+
+
+

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI> Previous message: <A HREF="017094.html">[Mono-bugs] [Bug 59638][Blo] Changed - MONO Beta 2 bug with XmlSerializer member ordering
</A></li>
	<LI> Next message: <A HREF="017096.html">[Mono-bugs] [Bug 58707][Maj] Changed - Exception when trying to AppDomain.Unload()
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#17095">[ date ]</a>
              <a href="thread.html#17095">[ thread ]</a>
              <a href="subject.html#17095">[ subject ]</a>
              <a href="author.html#17095">[ author ]</a>
         </LI>
       </UL>
</body></html>
